### ISSUE TITLE
python3 是否支持

### ISSUE THREAD

**Issue by taoshi006** [THUCSTHanxu13/TensorFlow-TransX#1]
我通过python3 运行transE.py  报段错误。

**Comment by Bryan2Chow** [comment]
我也是用python3 运行transE.py 报错两行：Input Files Path : .
                                                                      Segmentation fault

**Comment by THUCSTHanxu13** [comment]
请把https://github.com/THUCSTHanxu13/TensorFlow-TransX/blob/master/init.cpp里面的文件路径改掉，然后重新编译c代码

**Comment by THUCSTHanxu13** [comment]
话说，这个代码很久不维护了，东西都到https://github.com/thunlp/openke里了

**Comment by Bryan2Chow** [comment]
Segmentation Fault问题解决，  现在将TensorFlow版本改为0.12（pip install TensorFlow== 0.12）,并且是在python2中执行
